version: '2.1'
services:
  academy-api:
    build: .
    environment:
      PORT: '5500'
      SHOW_URLS: 'true'
      CHATS_URL: '192.168.99.102'
      CHATS_PORT: '8000'
      CHATS_ENTRY: 'chats'
    ports:
      - '5500:5500'
