version: '2.1'
services:
  academy-api:
    build: .
    environment:
      PORT: '5500'
      SHOW_URLS: 'true'
      CHATS_URL: '192.168.99.102'
      CHATS_PORT: '8000'
      CHATS_ENTRY: 'chats'
      USERS_URL: '192.168.99.110'
      USERS_PORT: '3000'
      USERS_ENTRY: 'users'
      TESTS_ENTRY: 'tests'
      NOTIF_URL: '192.168.99.101'
      NOTIF_PORT: '9000'
      NOTIF_ENTRY: 'notification'
      USDEV_ENTRY: 'user_device'

      
    ports:
      - '5500:5500'
