version: '2.1'
services:
  academy-api:
    build: .
    environment:
      PORT: '80'
      SHOW_URLS: 'true'
      CHATS_URL: '10.128.0.7'
      CHATS_PORT: '80'
      CHATS_ENTRY: 'chats'
      AUTH_URL: '10.150.0.5'
      AUTH_PORT: '80'
      AUTH_ENTRY: 'login'
      USERS_URL: '10.158.0.2'
      USERS_PORT: '80'
      USERS_ENTRY: 'users'
      TESTS_ENTRY: 'tests'
      FRIENDS_ENTRY: 'friends'
      NOTIF_URL: '10.128.0.6'
      NOTIF_PORT: '80'
      NOTIF_ENTRY: 'notification'
      USDEV_ENTRY: 'user_device'
      CHATROOM_URL: '10.128.0.4'
      CHATROOM_PORT: '80'

      
    ports:
      - '80:80'
